#%RAML 1.0
title: Employee API
version: v1
baseUri: http://localhost:8081/api
mediaType: application/json

securitySchemes:
  basicAuth:
    description: |
      This API supports Basic Authentication. 
      Default credentials: admin/password123
    type: Basic Authentication

types:
  Employee:
    properties:
      id: number
      firstName: string
      lastName: string
      email: string
      departmentId: number
      hireDate: date-only

/employees:
  securedBy: [basicAuth]
  get:
    description: Get all employees
    responses:
      200:
        body:
          type: Employee[]
      401:
        body:
          type: object
          properties:
            error: string
            message: string
  post:
    description: Create a new employee
    body:
      type: Employee
    responses:
      201:
        body:
          type: Employee
      401:
        body:
          type: object
          properties:
            error: string
            message: string
  /{id}:
    securedBy: [basicAuth]
    get:
      description: Get employee by ID
      responses:
        200:
          body:
            type: Employee
        401:
          body:
            type: object
            properties:
              error: string
              message: string
        404:
          body:
            type: object
            properties:
              message: string
    put:
      description: Update an employee
      body:
        type: Employee
      responses:
        200:
          body:
            type: Employee
        401:
          body:
            type: object
            properties:
              error: string
              message: string
        404:
          body:
            type: object
            properties:
              message: string
    delete:
      description: Delete an employee
      responses:
        204:
        401:
          body:
            type: object
            properties:
              error: string
              message: string
        404:
          body:
            type: object
            properties:
              message: string
